DROP TABLE IF EXISTS EMPLOYEES;
DROP TABLE IF EXISTS DEPARTMENTS;
  
  CREATE TABLE DEPARTMENTS
   (	DEPARTMENT_ID INT PRIMARY KEY, 
	DEPARTMENT_NAME VARCHAR(250) NOT NULL, 
	MANAGER_ID INT
   ) ;
   
     CREATE TABLE EMPLOYEES 
   (	EMPLOYEE_ID INT PRIMARY KEY, 
		FIRST_NAME VARCHAR(250) NOT NULL, 
		LAST_NAME VARCHAR(250) NOT NULL, 
		EMAIL VARCHAR(250), 
		PHONE_NUMBER VARCHAR(250), 
		HIRE_DATE DATE, 
		SALARY INT, 
		MANAGER_ID INT, 
		DEPARTMENT_ID INT
	 );